"""create_all_cms_tables

Revision ID: 6861910dfa99
Revises: 7583eb2df4d8
Create Date: 2026-10-05 14:55:59.677113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6861910dfa99'
down_revision: Union[str, Sequence[str], None] = '7583eb2df4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year_name', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('office_location', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('badge', sa.String(length=32), nullable=True),
    sa.Column('badge_type', sa.String(length=32), nullable=True),
    sa.Column('department_name', sa.String(length=128), nullable=True),
    sa.Column('footer', sa.String(length=128), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_category'), 'announcements', ['category'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('batch_name', sa.String(length=32), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_department_id'), 'batches', ['department_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('building', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('term_type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_academic_year_id'), 'semesters', ['academic_year_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('designation', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cabin_number', sa.String(length=32), nullable=True),
    sa.Column('qualifications', sa.String(length=128), nullable=True),
    sa.Column('experience', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_department_id'), 'staff', ['department_id'], unique=False)
    op.create_index(op.f('ix_staff_faculty_id'), 'staff', ['faculty_id'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('reads_count', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_course_id'), 'materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_materials_uploaded_by'), 'materials', ['uploaded_by'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_batch_id'), 'sections', ['batch_id'], unique=False)
    op.create_table('announcement_recipients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_recipients_announcement_id'), 'announcement_recipients', ['announcement_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_section_id'), 'course_offerings', ['section_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_semester_id'), 'course_offerings', ['semester_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_staff_id'), 'course_offerings', ['staff_id'], unique=False)
    op.create_table('material_downloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_downloads_material_id'), 'material_downloads', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_downloads_user_id'), 'material_downloads', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_mentor_id', sa.Uuid(), nullable=True),
    sa.Column('roll_number', sa.String(length=32), nullable=False),
    sa.Column('register_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('parent_name', sa.String(length=128), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_mentor_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_batch_id'), 'students', ['batch_id'], unique=False)
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_register_number'), 'students', ['register_number'], unique=True)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_index(op.f('ix_students_section_id'), 'students', ['section_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('lecture_type', sa.String(length=32), nullable=False),
    sa.Column('batch_split', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'day_of_week', 'period_id', name='uq_room_day_period'),
    sa.UniqueConstraint('section_id', 'day_of_week', 'period_id', name='uq_section_day_period'),
    sa.UniqueConstraint('staff_id', 'day_of_week', 'period_id', name='uq_staff_day_period')
    )
    op.create_index(op.f('ix_timetable_entries_course_id'), 'timetable_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_day_of_week'), 'timetable_entries', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetable_entries_period_id'), 'timetable_entries', ['period_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_room_id'), 'timetable_entries', ['room_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_section_id'), 'timetable_entries', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_staff_id'), 'timetable_entries', ['staff_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timetable_entry_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('conducted_hours', sa.Integer(), nullable=False),
    sa.Column('topic_covered', sa.String(length=255), nullable=True),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('od_count', sa.Integer(), nullable=False),
    sa.Column('total_marked', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_entry_id', 'date', name='uq_timetable_session_date')
    )
    op.create_index(op.f('ix_attendance_sessions_date'), 'attendance_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_staff_id'), 'attendance_sessions', ['staff_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_timetable_entry_id'), 'attendance_sessions', ['timetable_entry_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_session_student')
    )
    op.create_index(op.f('ix_attendance_records_attendance_session_id'), 'attendance_records', ['attendance_session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_sessions_timetable_entry_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_staff_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_date'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_timetable_entries_staff_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_section_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_room_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_period_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_day_of_week'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_register_number'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_batch_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_material_downloads_user_id'), table_name='material_downloads')
    op.drop_index(op.f('ix_material_downloads_material_id'), table_name='material_downloads')
    op.drop_table('material_downloads')
    op.drop_index(op.f('ix_course_offerings_staff_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_semester_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_section_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_id'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_announcement_recipients_announcement_id'), table_name='announcement_recipients')
    op.drop_table('announcement_recipients')
    op.drop_index(op.f('ix_sections_batch_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_materials_uploaded_by'), table_name='materials')
    op.drop_index(op.f('ix_materials_course_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_staff_faculty_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_department_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_semesters_academic_year_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_batches_department_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_announcements_category'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.drop_table('users')
    op.drop_table('periods')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
